<?php

function tppsC_menu() {
  $items = array();
  
  $items['admin/config/content/tppsC'] = array(
    'title' => 'tppsC',
    'description' => 'Configuration for the tppsC module',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('tppsC_form'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_CALLBACK,
  );

  $items['tppsC'] = array (
    'title' => 'Internal tppsC Pipeline',
    'description' => 'aka lets get tppsC',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('tppsC_form'),
    'access callback' => TRUE
  );
  
  return $items;
}

function tppsC_form($form, &$form_state) { 

  $form['DOI'] = array(
    '#type' => 'textfield',
    '#title' => t('DOI:'),
    '#size' => 40,
    '#maxlength' => 100,
    '#required' => TRUE,
  );

  $species_dropdown_option = array(
    '1' => '1',
    '2' => '2',
    '3' => '3',
    '4' => '4',
    '5' => '5',
  );

  $form['species_dropdown'] = array(
    '#prefix' => '<div class="container-inline">',
    '#type' => 'select',
    '#title' => t('How many species are there in the study?'),
    '#options' => $species_dropdown_option,
    '#suffix' => '</div>',
    '#required' => TRUE,
  );

  $study_type_options = array(
    'G' => 'Genotype',
    'P' => 'Phenotype',
    'E' => 'Environment',
    'GxP' => 'Genotype x Phenotype',
    'GxE' => 'Genotype x Environment',
    'PxE' => 'Phenotype x Environment',
    'GxPxE' => 'Genotype x Phenotype x Environment',
  );

  $form['study_type'] = array(
    '#type' => 'select',
    '#title' => t('Study Type:'),
    '#options' => $study_type_options,
    '#required' => TRUE,
  );

  $genotype_marker_types = array(
    'SNPs' => 'SNPs',
    'SSRs/cpSSRs' => 'SSRs/cpSSRs',
    'Other' => 'Other',
  );

  $form['genotype_marker_type'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Genotype Marker Type:'),
    '#options' => $genotype_marker_types,
    '#states' => array(
      'visible' => array(
        array(
          array('select[name="study_type"]' => array('value' => 'G')),
          'or',
          array('select[name="study_type"]' => array('value' => 'GxE')),
          'or',
          array('select[name="study_type"]' => array('value' => 'GxP')),
          'or',
          array('select[name="study_type"]' => array('value' => 'GxPxE')),
        )
      ),
    ),
  );

  $form['genotype_file_SNPs'] = array(
    '#type' => 'file',
    '#title' => t('SNPs File Upload'),
    '#description' => t('Please upload a .vcf file with the SNPs information.'),
    '#upload_validators' => array('file_validate_extensions' => array('vcf')),
    '#states' => array(
      'visible' => array(
        ':input[name="genotype_marker_type[SNPs]"]' => array('checked' => TRUE),
      ),
    ),
  );

  $form['genotype_file_SSRs'] = array(
    '#type' => 'file',
    '#title' => t('SSRs/cpSSRs File Upload'),
    '#description' => t('Please upload an excel file with the SSRs/cpSSRs information.'),
    '#states' => array(
      'visible' => array(
        ':input[name="genotype_marker_type[SSRs/cpSSRs]"]' => array('checked' => TRUE),
      ),
    ),
  );

  $form['genotype_file_SSRs_header_check'] = array(
    '#type' => 'checkbox',
    '#title' => t('My file does not have a header'),
    '#states' => array(
      'visible' => array(
        ':input[name="genotype_marker_type[SSRs/cpSSRs]"]' => array('checked' => TRUE),
      ),
    ),
  );

  $form['genotype_file_other'] = array(
    '#type' => 'file',
    '#title' => t('Other Genotype File Upload'),
    '#description' => t('Please upload an excel file with the Genotype information.'),
    '#states' => array(
      'visible' => array(
        ':input[name="genotype_marker_type[Other]"]' => array('checked' => TRUE),
      ),
    ),
  );

  $form['genotype_file_other_header_check'] = array(
    '#type' => 'checkbox',
    '#title' => t('My file does not have a header'),
    '#states' => array(
      'visible' => array(
        ':input[name="genotype_marker_type[Other]"]' => array('checked' => TRUE),
      ),
    ),
  );


  $form['phenotype_file_upload'] = array(
    '#type' => 'file',
    '#title' => t('Phenotype File Upload'),
    '#description' => t('Optional: Upload an excel file of phenotypic data,'),
    '#states' => array(
      'visible' => array(
        array(
          array('select[name="study_type"]' => array('value' => 'P')),
          'or',
          array('select[name="study_type"]' => array('value' => 'PxE')),
          'or',
          array('select[name="study_type"]' => array('value' => 'GxP')),
          'or',
          array('select[name="study_type"]' => array('value' => 'GxPxE')),
        )
      ),
    ),
  );

  $form['phenotype_header_check'] = array(
    '#type' => 'checkbox',
    '#title' => t('My file does not have a header'),
    '#states' => array(
      'visible' => array(
        array(
          array('select[name="study_type"]' => array('value' => 'P')),
          'or',
          array('select[name="study_type"]' => array('value' => 'PxE')),
          'or',
          array('select[name="study_type"]' => array('value' => 'GxP')),
          'or',
          array('select[name="study_type"]' => array('value' => 'GxPxE')),
        )
      ),
    ),
  );

  $form['environment_file_upload'] = array(
    '#type' => 'file',
    '#title' => t('Environment File Upload'),
    '#description' => t('Optional: Upload an excel file of enviornmental data.'),
    '#states' => array(
      'visible' => array(
        array(
          array('select[name="study_type"]' => array('value' => 'E')),
          'or',
          array('select[name="study_type"]' => array('value' => 'PxE')),
          'or',
          array('select[name="study_type"]' => array('value' => 'GxE')),
          'or',
          array('select[name="study_type"]' => array('value' => 'GxPxE')),
        )
      ),
    ),
  );

  $form['enviornment_header_check'] = array(
    '#type' => 'checkbox',
    '#title' => t('My file does not have a header'),
    '#states' => array(
      'visible' => array(
        array(
          array('select[name="study_type"]' => array('value' => 'E')),
          'or',
          array('select[name="study_type"]' => array('value' => 'PxE')),
          'or',
          array('select[name="study_type"]' => array('value' => 'GxE')),
          'or',
          array('select[name="study_type"]' => array('value' => 'GxPxE')),
        )
      ),
    ),
  );

  $study_design_options = array(
    'Natural Population' => 'Natural Population',
    'Growth Chamber' => 'Growth Chamber',
    'Greenhouse' => 'Greenhouse',
    'Common Garden' => 'Common Garden',
    'Plantation' => 'Plantation',
  );

  $form['study_design'] = array(
    '#type' => 'select',
    '#title' => t('Study Design:'),
    '#options' => $study_design_options,
    '#required' => TRUE,
  );

  $study_location_options = array(
    'WGS 84' => 'Latitude/Longitude (WGS 84)',
    'NAD 83' => 'Latitude/Longitude (NAD 83)',
    'ETRS 89' => 'Latitude/Longitude (ETRS 89)',
    'Custom Location' => 'Custom Location',
  );

  $form['study_location'] = array(
    '#type' => 'select',
    '#title' => t('Study Location:'),
    '#options' => $study_location_options,
    '#required' => TRUE,
  );

  $form['study_location_states_exact'] = array(
    '#type' => 'textfield',
    '#title' => t('Coordinates:'),
    '#states' => array(
      'visible' => array(
        array(
          array('select[name="study_location"]' => array('value' => 'WGS 84')),
          'or',
          array('select[name="study_location"]' => array('value' => 'NAD 83')),
          'or',
          array('select[name="study_location"]' => array('value' => 'ETRS 89')),
        )
      ),
    ),
    '#description' => t('Accepted Formats are Degrees Minutes Seconds, Degrees Decimal Minutes, and Decimal Degrees.'),
  );

  $form['study_location_states_custom'] = array(
    '#type' => 'textfield',
    '#title' => t('Custom Location:'),
    '#description' => t('Ex: Street Address, or other location formats.'),
    '#states' => array(
      'visible' => array(
        'select[name="study_location"]' => array('value' => 'Custom Location'),
      ),
    ),
  );

  $form['tree_location_data'] = array(
    '#type' => 'file',
    '#title' => t('Tree Accession File'),
    '#description' => t('Please provide a spreadsheet with columns for the Tree ID and the location of trees used in this study'),
  );


  $form['submit_button'] = array('#type' => 'submit', '#value' => t('Submit'));

  return $form;

}

function tppsC_form_validate($form, &$form_state) {
}

function tppsC_form_submit($form, &$form_state) {
  $DOI = $form_state['values']['DOI'];
  $studyType = $form_state['values']['study_type'];
  $studyDesign = $form_state['values']['study_design'];
  $studyLocation = $form_state['values']['study_location'];
  
  if ($studyLocation == 'WGS 84' or $studyLocation = 'NAD 83' or $studyLocation = 'ETRS 89') {
    $studyLocationCoord = $form_state['values']['study_location_states_exact'];
  }
  elseif ($studyLocation == 'Custom Location') {
    $studyLocationCoord = $form_state['values']['study_location_states_custom'];
  }

  $data = array(
    'DOI' => $DOI,
    'studyType' => $studyType,
    'studyDesign' => $studyDesign,
    'studyLocation' => $studyLocation,
    'studyLocationCoord' => $studyLocationCoord,
  );

  drupal_write_record('node', $data);

}

function tppsC_permission() {
  return array(
    'access tppsC content' => array(
      'title' => t('Access content for the tppsC module'),
     )
  );

}

function tppsC_help($path, $arg) {
  switch ($path) {
    case "admin/help#tppsC":
      return t("my custom internal tppsC module");
      break;
  }

}

